services:
  blogapi:
    image: ${DOCKER_REGISTRY-}blogapi
    container_name: blog.api
    build:
      context: .
      dockerfile: BlogApi/Dockerfile
    ports:
    - "5000:5000"
    - "5001:5001"

  blog.database:
     image: postgres:latest
     container_name: blog.databse
     environment:
         - POSTGRES_DB=blog
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=password
     volumes:
        - ./.containers/blog-db:/var/lib/postgresql/data
     ports:
        - 5432:5432

