services:
  blogapi:
    container_name: blog-api
    depends_on:
        db:
            condition: service_healthy
    build:
      context: ./src
      dockerfile: ../BlogApi/Dockerfile

    networks:
        - mynetwork

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlConnection=Host=db;Port=5432;Database=blog;Username=postgres;Password=password
    ports:
    - "5000:5000"
    - "5001:5001"

  db:
     image: postgres:latest
     container_name: blog.databse
     restart: always
     environment:
         - POSTGRES_DB=blog
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=password
     volumes:
        - postgres_data:/var/lib/postgresql/data
     ports:
        - "4400:80"
        - "5432:5432"
     healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

     networks:
      - mynetwork   
volumes:
  postgres_data:

networks:
  mynetwork:

