services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: blogapi
    depends_on:
      db:
        condition: service_healthy
    
    networks:
      - mynetwork

    environment:
      # - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__sqlConnection=Host=db;Port=5432;Database=blogapi;Username=postgres;Password=password

    ports:
       - "8080:80"
       - "8081:443"

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogapi
    
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
      
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:

