name: Build and deploy ASP.Net Core app to Azure Web App - blogapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore BlogApi.sln

      - name: Build with dotnet
        run: dotnet build BlogApi.sln --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish BlogApi.sln -c Release -o ./publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B52F7064CAA34029AACED613F9F6814A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FEBBF7D8D1104531B927B576258A6756 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_813676E37593492E9D6158F00CF32EA8 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'blogapi'
          slot-name: 'Production'
          package: ./publish
